name: Build Rust Application

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - runner-os: ubuntu-latest
            os: linux-amd64
          - runner-os: macos-13
            os: macos-amd64
          - runner-os: macos-latest
            os: macos-amd64
          - runner-os: windows-latest
            os: windows-amd64

    runs-on: ${{ matrix.platform.runner-os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-binary-${{ matrix.platform.os }}
        path: target/release/ort-sample
